import { useEffect, useState } from "react";
import { collection, query, orderBy, limit, getDocs } from "firebase/firestore";
import { db } from "../../firebase/config";

interface Insight {
  id: string;
  title: string;
  description: string;
  type: "MORTALITY_CLUSTER" | "RESPONSE_TIME" | "GENERAL";
  severity: "HIGH" | "MEDIUM" | "LOW";
}

export function WardInsights() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchInsights() {
      try {
        // Query the `/insights` collection generated by the `generatePatternInsights` Cloud Function
        const q = query(
          collection(db, "insights"),
          orderBy("createdAt", "desc"),
          limit(1) // Get the latest weekly report
        );
        
        // Mocking the backend AI payload for now
        console.log("Mocking insights from backend...");
        
        setTimeout(() => {
          setInsights([
            {
              id: "ins-1",
              title: "Mortality Cluster Detected",
              description: "A 15% spike in DROUGHT-related mortality was detected in Ward 42 over the last 14 days, primarily affecting Neem saplings planted by Green Earth NGO.",
              type: "MORTALITY_CLUSTER",
              severity: "HIGH"
            },
            {
              id: "ins-2",
              title: "Stewardship Bottleneck",
              description: "Custodian response times for WATER_NEEDED incidents in Ward 17 have degraded to an average of 96 hours (up from 48 hours). Recommendation: Redistribute assignments.",
              type: "RESPONSE_TIME",
              severity: "MEDIUM"
            },
            {
              id: "ins-3",
              title: "Positive Trend: Rapid Resolution",
              description: "Rotary Club East achieved a 98% on-time resolution rate this week, the highest across all active organizations.",
              type: "GENERAL",
              severity: "LOW"
            }
          ]);
          setLoading(false);
        }, 800);

      } catch (err) {
        console.error("Failed to load AI insights", err);
        setLoading(false);
      }
    }
    fetchInsights();
  }, []);

  if (loading) {
    return <div className="p-12 text-center text-slate-bark animate-pulse">Running AI Pattern Analysis...</div>;
  }

  return (
    <div className="flex flex-col gap-8 animate-fade-up">
      <div>
        <h2 className="font-display text-3xl text-ink-bark mb-4">AI Pattern Insights</h2>
        <p className="font-sans text-sm text-slate-bark mb-6">
          Weekly plain-language summaries generated by analyzing mortality records, incident clusters, and response times across the ward.
        </p>
        
        <div className="flex flex-col gap-4">
          {insights.map(insight => {
            let borderClass = "border-field-parchment-dark";
            let bgClass = "bg-white";
            let icon = "💡";

            if (insight.severity === "HIGH") {
              borderClass = "border-laterite-clay/30";
              bgClass = "bg-laterite-clay/5";
              icon = "⚠️";
            } else if (insight.severity === "MEDIUM") {
              borderClass = "border-turmeric-ochre/30";
              bgClass = "bg-turmeric-ochre/5";
              icon = "📊";
            } else {
              borderClass = "border-moss-canopy/30";
              bgClass = "bg-moss-canopy/5";
              icon = "✨";
            }

            return (
              <div key={insight.id} className={`p-6 rounded-tag border ${borderClass} ${bgClass} flex gap-4 items-start`}>
                <div className="text-2xl mt-1">{icon}</div>
                <div>
                  <h3 className="font-sans text-lg font-medium text-ink-bark">{insight.title}</h3>
                  <p className="font-sans text-base text-slate-bark mt-2 leading-relaxed">
                    {insight.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
